### ISSUE TITLE
queue.read should be able to block

### ISSUE THREAD

**Issue by JarekSed** [bcoe/karait#4]
It would be nice if queue.read could block until data is available. I implemented this in the python library  [here](https://github.com/JarekSed/karait). I don't know ruby at all, and the concept of blocking might not really make sense for the node.js version, so I only did the python one for now.

**Comment by bcoe** [comment]
Hey, send me a pull request with that code I don't think that's an insane feature to add. I can add it for Ruby shortly too.

**Comment by bcoe** [comment]
I pulled your code in, this option is now available with a few minor changes:
- I changed the optional parameters to :block, :polling_interval, and :polling_polling_timeout thought this was clearer.
- I pulled the blocking logic into private helper methods.

I've pushed new versions of the Ruby and Python libraries and tagged a release, thanks for the contribution! please keep feedback coming as you work with the library.
