### ISSUE TITLE
request atomic write()

### ISSUE THREAD

**Issue by ZoomQuiet** [bcoe/karait#6]
thanx for the simple and pythonic MQ base MongoDB;
- commonly, karait had to accept multi-message-sender
- so, duplicate message always happened
- so, we realy need the karait.write() lilke as $upset :
  - point unique key
  - if there is't same message, write into new
  - else there is same message, cancel write, retuen None

hope result as:

``` python
queue.write({'pid':123, 'action': 'wget ...'},
    unique='pid')
```

this feature should append karait?

**Comment by bcoe** [comment]
This sounds like a useful feature, and I would love to help solve your use-case better :) I will add this when I have a bit of time.

**Comment by ZoomQuiet** [comment]
thanx for all ;-)
in fact, as one realy wokring TaskQueue,
the beanstalkd is the tiny and perfect:
    https://github.com/kr/beanstalkd/blob/master/doc/protocol.txt#L81
of course, beanstalkd can not support serialized/distributed ...
so Karait base MongoDB,the perfect NoSQL works!
if Karait can support the TaskQueue Flow like beanstalkd;
that means wonderful!

**Comment by bcoe** [comment]
I've been thinking about how you'd pull this functionality off:
- An upsert doesn't do the trick, because the last writer to insert into the queue would overwrite the older insert.

Unless I'm crazy, I think the only way to pull this off in an atomic way would be using db.eval().
- func = function() {r = db.messages.find_one({unique_field: unique_field}); if(r) { return }; db.messages.insert(document); }
- db.eval(func, {unique_field: value, document: doc}})

**Comment by ZoomQuiet** [comment]
Huuuu, simple is better ;-)

i believe in:"every problem can be resolve by plugin one more level!"

so unnecessary fight with one collections?
- add one uniqe seed collections, such as karait_uniqe
- document as:

``` python
{'routing_key':''
    ,'uniqu_key':''
    ,'inserted_var':['',]
    ,'_meta':{'ref_id':'point which doc. created the uniqe seed'
        ,'XXX':'others need meta info.'
    }

}
```
- so 1st insert with uniqe ref. , copy the var. into karait_uniqe.inserted_var
- the next insert try,check the var. if had inserted, breakout it!

**Comment by bcoe** [comment]
I think I've added functionality that will support what you're looking for, when writing:

_write_ will now return True if a write succeeds and false if it fails.

See this unit test: https://github.com/bcoe/karait/commit/e983f4644adcc05036dd2f3db794edee6e363e57#L1R203

Play with this, and if it does the trick I'll add the feature to the Ruby and Python libraries as well. I'm mostly interested in performance.

_NOTE:_ To get reasonable performance you will need to ensure that an index is placed on unique keys you insert with.

**Comment by bcoe** [comment]
I have added this functionality to the Node.js and Ruby clients.
