### ISSUE TITLE
visibility_timeout NOT WORK?!

### ISSUE THREAD

**Issue by ZoomQuiet** [bcoe/karait#7]
as doc, i guess the visibility_timeout will auto recover overtime message process?!
- so i expected as:

``` python
queue = Queue()
msg = queue.read(routing_key='for_bar',visibility_timeout=1.0)[0]
time.sleep(3)
msg.delete()

#   throw out some error here! so i know process timeover!
```
- but in my case:

``` python
msg = queue.read(routing_key='for_bar',visibility_timeout=1.0)[0]
print "msg.is_expired()", msg.is_expired()
print CCFG.CONNFAD['karait']['messages'].find_one({'sid':msg.sid}
    ,{'_id':0,'sid':1,'_meta.expire':1,'_meta.expired':1,'_meta.visible_after':1})
time.sleep(3)
print time.time()
print "msg.is_expired()", msg.is_expired()
print CCFG.CONNFAD['karait']['messages'].find_one({'sid':msg.sid}
    ,{'_id':0,'sid':1,'_meta.expire':1,'_meta.expired':1,'_meta.visible_after':1})
msg.delete()
print "msg.is_expired()", msg.is_expired()
print CCFG.CONNFAD['karait']['messages'].find_one({'sid':msg.sid}
    ,{'_id':0,'sid':1,'_meta.expire':1,'_meta.expired':1,'_meta.visible_after':1})

```

export is:

```
1322708234.24
msg.is_expired() False
{u'_meta': {u'visible_after': 1322708235.236205
        , u'expire': -1.0
        , u'expired': False}
    , u'sid': u'0002679'}
1322708237.32
msg.is_expired() False
{u'_meta': {u'visible_after': 1322708235.236205
        , u'expire': -1.0
        , u'expired': False}
    , u'sid': u'0002679'}
msg.is_expired() False
{u'_meta': {u'visible_after': 1322708235.236205
        , u'expire': -1.0
        , u'expired': True}
    , u'sid': u'0002679'}
```
- checked code,i guess:
  - _check_if_expired() is just worked one time when `message.__init__()`
  - and only check _meta.expire with _meta.timestamp
  - but the visibility_timeout only update into visible_after, NOT relation with is_expired()
  - means:
    - is_expired equal message.delete()
    - visibility_timeout never checked, just update visible_after,make next read() cancel this message
- so that is unacceptable ;-(
  - for the word means
  - visibility_timeout JUST should work as:
    - when read() the message, but timeover, THROW ERROR for it!
    - when realy timeover, the message NEED recovered as normoal message, can read out by other process

that all

**Comment by bcoe** [comment]
I think there's a bit of confusion about the visiblity_timeout functionality.

Setting visibility timeout simply makes it so other processes reading the queue do not observe that message for a set amount of time (this is modeled closely after SQS).

When writing a message into the queue you can set an 'expire' value which indicates how long it will be available in the queue for, i.e., a message with an expiry of 3 seconds will not be read from the queue 5 seconds after it is placed within the queue, even if it has never been consumed.

What's the actual use-case you're trying to solve? slightly confused.

**Comment by ZoomQuiet** [comment]
`can set an 'expire'` ;-( not notice this...

soo sorry my poor english;
as u remind, i get it:

```
- visiblity_timeout Atomic read() :

    - when timeout,other process can read out the same message
    - whatever maybe some process is working base this message

- _meta.expire can setup,when write() :

    - when timeout, the message is gone, other process can not read it again.
    - whatever maybe the broken process never work done base this message
```

that is clean and simple ;-)

but the parameter name is a bit confusion ,suggest:

```
- write(validity=3.0) 

    - after 3 seconds,the message will invalidation which writed;
    - means the message's status as never be write, same nonexistent

- read(validity=3.0) 

    - after 3 seconds,the message will invalidation which readed;
    - means the message's status as never be read, recovered, be normal
```
